"""'add_post_is_public'

Revision ID: 69e2ae944384
Revises: d3f81a993362
Create Date: 2024-12-11 20:42:33.170563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e2ae944384'
down_revision = 'd3f81a993362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_posts_is_public'), ['is_public'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_is_public'))
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
