"""'initial'

Revision ID: d3f81a993362
Revises: fe9af4cf1404
Create Date: 2024-12-05 15:01:48.676452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f81a993362'
down_revision = 'fe9af4cf1404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=True),
    sa.Column('body_md', sa.TEXT(), nullable=True),
    sa.Column('body_html', sa.TEXT(), nullable=True),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('last_modify', sa.DATETIME(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('stars', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='post_category'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
